apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-4
  labels:
    app: nginx-app-4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app-4
  template:
    metadata:
      labels:
        app: nginx-app-4
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
